<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gravity</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!/usr/bin/env node</string>
	<key>foldingStartMarker</key>
	<string>^.*\b(func)\s*(\w+\s*)?\([^\)]*\)(\s*\{[^\}]*)?\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>Gravity</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|in|or|is|for|var|and|not|else|true|file|lazy|super|break|while|event|_func|_args|repeat|switch|return|extern|import|module|continue|internal|undefined)\b</string>
			<key>name</key>
			<string>keyword.control.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\btrue\b</string>
			<key>name</key>
			<string>constant.language.boolean.true.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#include\b</string>
			<key>name</key>
			<string>keyword.control.import.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bfalse\b</string>
			<key>name</key>
			<string>constant.language.boolean.false.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bnull\b</string>
			<key>name</key>
			<string>constant.language.null.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(class|enum|func|var)\b</string>
			<key>name</key>
			<string>storage.type.gravity</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gravity</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#!).*$\n?</string>
			<key>name</key>
			<string>keyword.control.import.gravity</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gravity</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.gravity</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*\*(?!/)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gravity</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(const|private|public|static|struct|default|get|set)\b</string>
			<key>name</key>
			<string>storage.modifier.gravity</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gravity</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(System)\b</string>
			<key>name</key>
			<string>entity.name.type.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\|=|\^=|&=|\-=|\+=|%=|\/=|\*=|~=|\*|\*\=|~|\^|!==|\||\|\||/|===|==|!=|==|&amp;|&amp;&amp;|!|&lt;=|&gt;=|\+|-|%|&gt;|&lt;)</string>
			<key>name</key>
			<string>keyword.operator.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>meta.brace.curly.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\;</string>
			<key>name</key>
			<string>punctuation.terminator.statement.gravity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>meta.delimiter.method.period.gravity</string>
		</dict>
			<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.gravity</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.gravity</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.gravity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.gravity</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.gravity</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.gravity</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.gravity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\\\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.punctuation.expression.begin.gravity</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.expression.gravity</string>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.punctuation.expression.end.gravity</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.gravity</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.gravity</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.range.begin.gravity</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.gravity</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.gravity</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.gravity</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.range.end.gravity</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[)(-?[0-9]+)?(\.\.\.?)(-?[0-9]+)?(\])</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gravity</string>
</dict>
</plist>